openapi: 3.0.0
info:
  title: Argent Bank API
  description: API pour gérer les comptes et transactions des utilisateurs
  version: 1.0.0

servers:
  - url: http://localhost:3001/api/v1

paths:
  /accounts:
    get:
      summary: Récupérer la liste des comptes de l'utilisateur
      description: Retourne tous les comptes associés à l'utilisateur connecté.
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
          description: ID de l'utilisateur pour récupérer ses comptes.
      responses:
        '200':
          description: Liste des comptes de l'utilisateur.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '404':
          description: Aucun compte trouvé pour cet utilisateur.

  /accounts/{accountId}:
    get:
      summary: Récupérer les détails d'un compte spécifique
      description: Retourne les informations détaillées d'un compte.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: ID du compte à afficher.
      responses:
        '200':
          description: Détails du compte.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Compte non trouvé.

  /accounts/{accountId}/transactions:
    get:
      summary: Récupérer les transactions d'un compte spécifique
      description: Retourne toutes les transactions associées à un compte.
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: ID du compte pour lequel récupérer les transactions.
        - in: query
          name: month
          schema:
            type: string
            format: date-time
          required: false
          description: Mois pour filtrer les transactions (format YYYY-MM).
      responses:
        '200':
          description: Liste des transactions du compte.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '404':
          description: Aucun compte ou transaction trouvé.

    post:
      summary: Ajouter une nouvelle transaction à un compte spécifique
      description: Ajoute une nouvelle transaction au compte spécifié
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: ID du compte auquel ajouter la transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTransaction'
      responses:
        '201':
          description: Transaction créée avec succès.
        '400':
          description: Requête invalide.

  /accounts/{accountId}/transactions/{transactionId}:
    put:
      summary: Modifier une transaction existante
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: ID du compte
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: ID de la transaction à modifier.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatedTransaction'
      responses:
        '200':
          description: Transaction mise à jour avec succès.
        '404':
          description: Transaction non trouvée.

    delete:
      summary: Supprimer une transaction spécifique
      parameters:
        - in: path
          name: accountId
          schema:
            type: string
          required: true
          description: ID du compte
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: ID de la transaction à supprimer.
      responses:
        '204':
          description: Transaction supprimée avec succès.
        '404':
          description: Transaction non trouvée

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        balance:
          type: number
        accountType:
          type: string
        createdAt:
          type: string
          format: date-time

    Transaction:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
        amount:
          type: number
        date:
          type: string
          format: date-time
        description:
          type: string
        category:
          type: string

    NewTransaction:
      type: object
      properties:
        amount:
          type: number
        description:
          type: string
        category:
          type: string
      required:
        - amount
        - description

    UpdatedTransaction:
      type: object
      properties:
        amount:
          type: number
        description:
          type: string
        category:
          type: string
